### ISSUE TITLE
Path not specified error

### ISSUE THREAD

**Issue by ryanpmccaffrey** [Tian312/EliIE#1]
Hi,
I encountered an error when running NamedEntityRecognition.py with your sample test.txt file.  Attached is a screen capture of the error.  I was running your code on a Windows 7 64-bit anaconda Python 2.7 virtual environment with all the required packages installed and MetaMap running.  It tells me "The system cannot find the path specified" even though I'm running the files from the EliIE directory.  Exactly how should the path be specified?  Thanks!

![screencapture](https://user-images.githubusercontent.com/5515646/35107080-01637d18-fc3e-11e7-8c2a-10b4d10da8f6.PNG)

**Comment by Tian312** [comment]
Hi
Thanks for the feedbacks.
This error is caused by different formatting in directory. My parser assumes linux/unix directory. 
To solve it, please modify [umls_identify.py](https://github.com/Tian312/EliIE/blob/master/features_dir/umls_identify.py#L16) line 12-14 to adapt windows format.
